@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

olcnePipeline(
  branchPattern: new BranchPattern(master: 'oracle/release/{{{.major}}}.{{{.minor}}}.{{{.patch}}}', feature: 'feature/.*'),
  containers: ['container-registry.oracle.com/olcne/k8s-sidecar:v{{{.major}}}.{{{.minor}}}.{{{.patch}}}': 'olcne/k8s-sidecar:v{{{.major}}}.{{{.minor}}}.{{{.patch}}}'],
        platforms: ['ol9'],
        architectures: ['x86_64', 'aarch64'],
        yumOL9Repos: ['ol9_appstream', 'ol9_baseos_latest'],
        customPlatformSteps: [
                ol9: [container: [enabled: true], buildContainerRpms: [enabled: true]],
        ]
)