@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

imagePipeline(
  branchPattern: new BranchPattern(master: 'oracle/release/2.1.3', feature: '(?!^release/.*$)(^.*$)'),
  containers: ['container-registry.oracle.com/olcne/k8s-sidecar:v2.1.3': 'olcne/k8s-sidecar:v2.1.3'],
        platforms: ['ol9'],
        architectures: ['x86_64', 'aarch64'],
        yumOL9Repos: ['ol9_appstream', 'ol9_baseos_latest'],
        customPlatformSteps: [
                ol9: [container: [enabled: true], buildContainerRpms: [enabled: true]],
        ],
        buildScript: "sh olm/build-image.sh"
)